# Generated by Django 4.1.1 on 2022-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="exam_reg_no",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="phone",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
