# Generated by Django 4.1.1 on 2022-10-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_enroll"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentinfo", name="cgpa",),
    ]
