# Generated by Django 4.1.1 on 2022-12-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_studentinfo_exam_reg_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="enroll",
            name="request_removal",
            field=models.BooleanField(default=False),
        ),
    ]
