# Generated by Django 4.1.1 on 2022-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_alter_courseinfo_hours_per_week_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseinfo", old_name="couse_code", new_name="course_code",
        ),
        migrations.RenameField(
            model_name="courseinfo", old_name="couse_name", new_name="course_name",
        ),
        migrations.AlterField(
            model_name="courseinfo",
            name="syllabus",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
