# Generated by Django 4.1.1 on 2022-09-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification",
            field=models.TextField(max_length=400),
        ),
    ]
