# Generated by Django 4.1.1 on 2022-10-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0007_alter_notification_publish_date_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="department",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="department.depprofileinfo",
            ),
        ),
    ]
