# Generated by Django 4.1.1 on 2022-10-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0010_teaches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaches",
            name="faculty",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="department.faculty"
            ),
        ),
    ]
