# Generated by Django 4.1.1 on 2022-10-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0011_alter_teaches_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaches",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="department.courseinfo"
            ),
        ),
    ]
