# Generated by Django 4.1.1 on 2022-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0012_alter_teaches_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinfo",
            name="seats_left",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
