# Generated by Django 4.1.1 on 2022-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0013_courseinfo_seats_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinfo",
            name="seats_left",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
