# Generated by Django 4.1.1 on 2022-11-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0015_alter_courseinfo_syllabus_programinfo_login_type"),
    ]

    operations = [
        migrations.DeleteModel(name="Login_type",),
    ]
